var fs = require("fs")
// fs.mkdirSync("node")
// fs.writeFileSync("node/rw.txt","Vatsal Desai")
// fs.appendFileSync("node/rw.txt"," How are you ?? 😁😜🤪💩🐱‍👤🐷🐶🐼🦘🐊🐬")
// data = fs.readFileSync("node/rw.txt")
// console.log(data)
// console.log(data.toString())
// fs.renameSync("node/rw.txt","node/write.txt")
fs.writeFileSync("node/write.txt","ohh hello panda🐼 !")
data = fs.readFileSync("node/write.txt")
console.log(data.toString())
// fs.unlinkSync("node/write.txt")
